### ISSUE TITLE
Hook shotting over spikes in phantom pyramid causes harm.

### ISSUE THREAD

**Issue by nightwishfan1** [usineur/Zelda3T#3]
I was playing this game, and got all the way to the phantom pyramid, and after a fair way in you should be able to hook shot over some spikes on the floor in a section, and progress.  However when doing this the game treats the situation as though you walked onto them when attempting to hook shot over them, and you instead can't progress beyond that point.  This shouldn't happen, and I've confirmed via a guide of the pc version of the game that this does not occur there, and therefore shouldn't be occurring in ports of it to other platforms.

For reference here is the youtube video https://www.youtube.com/watch?v=CroaUN3yQe0

between the times of 6:19 and 6:21 show the exact spot I encountered the issue noted above.  I would provide a save state right at that point, but from what I see I can't exactly save right at the point but in the dungeon I'm at, which only starts you at the start of it.  If a save file will help then I provide it since it will probably get you to the point indicated in the video quicker since I already made it there.  Thanks.

**Comment by usineur** [comment]
Yes, i need at the least a save.

**Comment by nightwishfan1** [comment]
There ya go.
[3t1.zip](https://github.com/usineur/Zelda3T/files/1399275/3t1.zip)

**Comment by usineur** [comment]
Ok... The bug is also present in the original engine, just test it on PC, original sources.

Link must be in a correct alignment with the targeted pole. I'm able to reproduce this problem when Link is slightly lower than the pole but the hook can grab them. In all other cases, everything is fine (PC or PS Vita).

It will be a "wontfix" for now, as it can be easily "bypassed "and as it only happened when there is spikes on the way.
